version: "3.7"

services:

  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: ecommerce
    ports:
      - '5432:5432'
    restart: always
    networks:
      - ecommerce-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
