spring:
  application:
    name: Spring-boot-3-crud-generator
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/changelog-master.yaml"
    liquibase-schema: liquibase

server:
  port: 9999
